### GENERAL SETTINGS ###

# Site settings
title: "Research Software"
description: "Research Software Criteria and Taxonomy"
baseurl: "/rseng" #important: start with /
url: ""

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge

permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#159958"
  primary_rgb: "21,153,88" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#F7F7F7"
  link: "#159958"
  link_hover: "#01b2fe"
  footer_heading: "#777"
  footer_content: "#bfc9d3"

# Making projects separate from posts
collections:
  taxonomy:
    output: true
    permalink: /taxonomy/:path/
  criteria:
    output: true
    permalink: /criteria/:path/

url: "https://rseng.github.io/rseng"
repo: "https://github.com/rseng/rseng"
future: true

defaults:
  -
    scope:
      path: "_taxonomy"
    values:
      layout: taxentry
  -
    scope:
      path: "_criteria"
    values:
      layout: catentry

  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
    future: true

    scope:
      path: "pages"
      type: "pages"
    values:
      layout: "base"


### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: twitter
    url: https://www.twitter.com/vsoch

twitter: vsoch


# Search settings
tipue_search:
  include:
    pages: false
    collections: [taxonomy, criteria]
  exclude:
    files: [index.md, search.html]

exclude:
  - Gemfile
  - Gemfile.lock
  - _templates
  - README.md
  - tests 

# asciinema defaults
asciicast:
    cols: "115"
    rows: "25"
    speed: "2.0"
    theme: "asciinema"

# asciinema
# tango
# solarized-dark
# solarized-light
# monokai
